[custom0]
binding=''
command='alacritty'
name='alacritty-terminal'

[custom1]
binding='<Control><Alt>t'
command='ghostty'
name='ghostty-terminal'

[custom2]
binding='<Control><Alt>m'
command='ghostty --working-directory=/home/stepan41k/Documents/workspace/p-manager -e "make run"'
name='p-manager'